services:
#  ui-pick-on-maps:
#    image: ghcr.io/calinvladth/ui_pick_on_maps:latest
#    environment:
#      - VITE_API_URL=$API_URL
  ui-pick-on-maps:
    container_name: ui-pick-on-maps
    build:
      context: ./ui/pick-on-maps
      target: prod
    environment:
      - NODE_ENV=production
      - VITE_API_URL=$API_URL
    ports:
      - '8080:8080'
    volumes:
      - ./ui/pick-on-maps/src:/usr/src/app/src
      - /usr/src/app/src/node_modules