name: Docker CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish image
        run: |
          docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.GHCR_TOKEN}} ghcr.io
          docker build customer -t ghcr.io/${{secrets.DOCKER_USERNAME}}/customer_service:latest
          docker push ghcr.io/${{secrets.DOCKER_USERNAME}}/customer_service:latest